
export const metadata = {
  title: "Generate new Assessment",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <>  
        {children}
    </>
  );
}
